# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Release

on: 
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.0"
      - name: Build Swift package
        run: swift build -c release --arch arm64 --arch x86_64  
        
      - name: Get Current Tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Run shell script with tag
        run: ./Scripts/release-artifactbundle.sh "${{ env.TAG_NAME }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nest-macos.artifactbundle.zip
            pkl/Nestfile.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
